# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eea56002d30bded81419c7e36a1b23f56cc2c730e05edc1c0f7749855d2f35f87d8615d3a5e403b340ade71a72a6849b6d06d0ed73598f454ce542ac56d092b

test:
  secret_key_base: e674395ca55d061ca399e18e4f8ab8a13ff2741a7e76709f5f5634891380db4a7e715d31b2d4e3ceddf02b48b31562f0e1fdfec6015d79034c7dbe205c9ac787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
